on:
  workflow_dispatch:
    inputs:
      environment:
        description: "choose environment"
        required: true
        type: choice
        options:
          - main
          - stage

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: deploy app
        run: echo "deploy app to ${{ inputs.environment }}"
